import { CondoProjectDetail } from "./types";

// Demo data so the full flow runs before Supabase is wired up.
export const MOCK_PROJECTS: CondoProjectDetail[] = [
  {
    id: "1",
    condo_id: "CA-0001",
    project_name: "Harbor Point Condominiums",
    address: "100 Marina Blvd",
    city: "San Diego",
    county: "San Diego",
    state: "CA",
    zip: "92101",
    warrantability: "warrantable",
    blacklisted: false,
    last_updated: "2026-04-12",
    hoa_name: "Harbor Point HOA",
    management_company: "Coastal Management Group",
    total_units: 240,
    units_sold_pct: 96,
    owner_occupied_pct: 71,
    investor_owned_pct: 29,
    single_entity_ownership_pct: 8,
    delinquency_pct: 3,
    reserve_funded_pct: 18,
    litigation: false,
    litigation_notes: null,
    commercial_space_pct: 0,
    master_insurance: true,
    questionnaire_source: "Coastal Management Group",
    notes: "Limited review eligible. Reserves above 10% threshold.",
  },
  {
    id: "2",
    condo_id: "IL-0002",
    project_name: "The Madison Lofts",
    address: "55 W Madison St",
    city: "Chicago",
    county: "Cook",
    state: "IL",
    zip: "60602",
    warrantability: "non_warrantable",
    blacklisted: false,
    last_updated: "2026-03-01",
    hoa_name: "Madison Lofts Association",
    management_company: "Midwest Property Partners",
    total_units: 88,
    units_sold_pct: 64,
    owner_occupied_pct: 40,
    investor_owned_pct: 60,
    single_entity_ownership_pct: 34,
    delinquency_pct: 22,
    reserve_funded_pct: 4,
    litigation: false,
    litigation_notes: null,
    commercial_space_pct: 31,
    master_insurance: true,
    questionnaire_source: "Midwest Property Partners",
    notes: "Single-entity ownership and delinquency exceed Fannie limits.",
  },
  {
    id: "3",
    condo_id: "TX-0003",
    project_name: "Riverside Gardens",
    address: "12 Riverside Dr",
    city: "Austin",
    county: "Travis",
    state: "TX",
    zip: "78701",
    warrantability: "non_warrantable",
    blacklisted: true,
    last_updated: "2025-11-20",
    hoa_name: "Riverside Gardens HOA",
    management_company: "Lone Star Community Mgmt",
    total_units: 150,
    units_sold_pct: 100,
    owner_occupied_pct: 80,
    investor_owned_pct: 20,
    single_entity_ownership_pct: 5,
    delinquency_pct: 6,
    reserve_funded_pct: 12,
    litigation: true,
    litigation_notes: "Active structural defect litigation against developer.",
    commercial_space_pct: 0,
    master_insurance: true,
    questionnaire_source: "Lone Star Community Mgmt",
    notes: "BLACKLISTED: active litigation. Do not proceed without legal review.",
  },
];
